sylius_twig_hooks:
    hooks:
        'sylius_admin.payment_method.index.content.grid':
            confirmation-modal-create-pay-pal:
                template: '@SyliusPayPalPlugin/admin/payment_method/grid/confirmation-modal-create-pay-pal.html.twig'
                priority: -100
