winzou_state_machine:
    sylius_payment:
        callbacks:
            before:
                refund_pay_pal_order:
                    on: [ 'refund' ]
                    do: [ '@sylius_paypal.processor.payment_refund', 'refund' ]
                    args: [ 'object' ]
        transitions:
            cancel:
                from: [ cart ]
                to: cancelled
